One error idk what is wrong messagerepo (7,8) error
/home/niej/Project/UniFiler/3_semester/ChirpFolder/chirper1st/Chirp/src/Chirp.Infrastructure/MessageRepository.cs(7,28): error CS0246: The type or namespace name 'IMessageRepository' could not be found (are you missing a using directive or an assembly reference?) [/home/niej/Project/UniFiler/3_semester/ChirpFolder/chirper1st/Chirp/src/Chirp.Infrastructure/Chirp.Infrastructure.csproj